PL.Web/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using BLL.Interface;
using DependencyResolver;
using Ninject;
using PL.WebApplication.Filters;
using PL.WebApplication.Models;
using System.Web.Security;
using System.Security.Principal;
using PL.WebApplication.DAL.Interface.Interfaces;

namespace PL.WebApplication.Controllers
{
    //[HandleError(ExceptionType = typeof(Exception), View = "Error")]
    [Authenticate]
    public class ServiceController : Controller
    {
        private static IAccountService service;
        IUsersRepository usersRepo;
        //BLL.Interface.AccountOwner user;

        public ServiceController(IUsersRepository repo)
        {
            usersRepo = repo;
        }

        static ServiceController()
        {
            var kernel = new StandardKernel();
            kernel.Unbind<ModelValidatorProvider>();
            kernel.ConfigurateResolver();
            service = kernel.Get<IAccountService>();
        }

        public ActionResult Index()
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);
            return this.View();
        }

        public ActionResult Deposit()
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);
            var accounts = service.GetPersonalAccounts(user).Select(a => (Models.BankAccount)a);
            return View(accounts);
        }

        // [ActionName("deposit")]
        [HttpPost]
        public ActionResult DepositTo(string iban)
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);
            Models.BankAccount acc = service.GetPersonalAccounts(user).Single(a => a.IBAN == iban);
            return View("DepositTo", acc);
        }

        [HttpPost]
        public ActionResult MakeDeposit(string iban, decimal amount)
        {
            //if (!amount.HasValue || amount <= 0)
            //{
            //    ModelState.AddModelError("deposit amount", "deposit amount must be a positive number");
            //}

            //if (ModelState.IsValid)
            //{
            try
            {
                service.MakeDeposit(iban, amount);
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            Models.BankAccount account = service.GetPersonalAccounts(usersRepo.GetByEmail(User.Identity.Name)).Single(a => a.IBAN == iban);
            if (ModelState.IsValid)
            {
                account = service.GetPersonalAccounts(usersRepo.GetByEmail(User.Identity.Name)).Single(a => a.IBAN == iban);
                var values = new RouteValueDictionary(account)
                    {
                        { "amount", amount }
                    };
                return RedirectToAction("DepositMade", values);
            }

            //}

            return View("DepositTo", account);
        }

        public ViewResult DepositMade(Models.BankAccount account, decimal amount)
        {
            ViewBag.Amount = amount;
            return View(account);
        }

        [HttpGet]
        public ActionResult Withdraw()
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);
            var accounts = service.GetPersonalAccounts(user).Select(a => (Models.BankAccount)a);
            return View(accounts);
        }

        // [ActionName("withdraw")]
        [HttpPost]
        public ViewResult WithdrawFrom(string iban)
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);
            Models.BankAccount acc = service.GetPersonalAccounts(user).Single(a => a.IBAN == iban);
            return View("WithdrawFrom", acc);
        }

        [HttpPost]
        public ActionResult MakeWithdrawal(string iban, decimal amount)
        {
            //if (!amount.HasValue || amount <= 0)
            //{
            //    ModelState.AddModelError("withdrawal amount", "withdrawal amount must be a positive number");
            //}

            //if (ModelState.IsValid)
            //{
            Models.BankAccount account = service.GetPersonalAccounts(usersRepo.GetByEmail(User.Identity.Name)).Single(a => a.IBAN == iban);
            try
            {
                service.MakeWithdrawal(iban, amount);
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            if (ModelState.IsValid)
            {
                account = service.GetPersonalAccounts(usersRepo.GetByEmail(User.Identity.Name)).Single(a => a.IBAN == account.IBAN);
                var values = new RouteValueDictionary(account)
                    {
                        { "amount" , amount }
                    };
                return RedirectToAction("WithdrawalMade", values);
            }
            //}

            return View("WithdrawFrom", account);
        }

        public ViewResult WithdrawalMade(Models.BankAccount account, decimal amount)
        {
            ViewBag.Amount = amount;
            return View(account);
        }

        [HttpGet]
        public ActionResult Transfer()
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);
            var accounts = service.GetPersonalAccounts(user).Select(a => (Models.BankAccount)a);
            return View(accounts);
        }

        // [ActionName("transfer")]
        [HttpPost]
        public ActionResult TransferToMy(string fromIBAN)
        {
            //var user = usersRepo.GetByEmail(User.Identity.Name);
            //var acc1 = service.GetPersonalAccounts(user).Single(a => a.IBAN == from);
            //var acc2 = service.GetPersonalAccounts(user).Single(a => a.IBAN == to);
            //return View("TransferBetween", new[] { acc1, (Models.BankAccount)acc2 });

            var user = usersRepo.GetByEmail(User.Identity.Name);
            ViewBag.Accounts = service.GetPersonalAccounts(user).Where(a => a.IBAN != fromIBAN).Select(a => (Models.BankAccount)a).ToArray();
            Models.BankAccount acc = service.GetPersonalAccounts(user).Single(a => a.IBAN == fromIBAN);
            return View(acc);
        }

        [HttpPost]
        public ActionResult TransferToMyAmount(string fromIBAN, string toIBAN)
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);
            var from = service.GetPersonalAccounts(user).Single(a => a.IBAN == fromIBAN);
            var to = service.GetPersonalAccounts(user).Single(a => a.IBAN == toIBAN);
            return View(new[] { from, (Models.BankAccount)to });
        }

        [HttpPost]
        public ActionResult TransferToAnothers(string fromIBAN)
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);
            //ViewBag.Accounts = service.GetPersonalAccounts(user).Where(a => a.IBAN != fromIBAN).Select(a => (Models.BankAccount)a).ToArray();
            Models.BankAccount acc = service.GetPersonalAccounts(user).Single(a => a.IBAN == fromIBAN);
            return View(acc);
        }

        public ActionResult GetAnothersAccount(string iban, string fromIBAN)
        {
            var acc = service.GetAccount(iban);
            if (acc == null)
            {
                return Content($"<i class='text-danger'>IBAN {iban} was not found.</i>");
            }
            else
            {
                if (acc.Owner.Email == User.Identity.Name)
                {
                    return Content("<i class='text-danger'>It is your own account.</i>");
                }
                else
                {
                    ViewBag.toIBAN = iban;
                    ViewBag.fromIBAN = fromIBAN;
                    return PartialView("_TransferToAnothersAmount", acc.Owner.FullName);
                }
            }
        }

        [HttpPost]
        public ActionResult MakeTransfer(string fromIBAN, string toIBAN, decimal amount)
        {
            //service.MakeWithdrawal(fromIBAN, amount);
            //service.MakeDeposit(toIBAN, amount);
            service.MakeTransfer(fromIBAN, toIBAN, amount);

            var user = usersRepo.GetByEmail(User.Identity.Name);

            Models.BankAccount acc = service.GetPersonalAccounts(user).Single(a => a.IBAN == fromIBAN);
            var values = new RouteValueDictionary(acc) { { "amount", amount } };
            return RedirectToAction("TransferMade", values);
        }

        public ViewResult TransferMade(Models.BankAccount from, decimal amount)
        {
            ViewBag.Amount = amount;
            return View(from);
        }

        [ActionName("create")]
        [HttpGet]
        public ActionResult CreateAccount()
        {
            return View();
        }

        [ActionName("create")]
        [HttpPost]
        public ActionResult CreateAccount(Models.NewAccount account)
        {
            if (ModelState.IsValid)
            {
                var user = usersRepo.GetByEmail(User.Identity.Name);
                var iban = service.OpenAccount(user, account.StartBalance);
                var acc = service.GetPersonalAccounts(user).Single(a => a.IBAN == iban);
                return RedirectToAction("Created", (Models.BankAccount)acc);
            }

            return View(account);
        }

        [HttpPost]
        public PartialViewResult GetAccountModal(string iban)
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);
            Models.BankAccount acc = service.GetPersonalAccounts(user).Single(a => a.IBAN == iban);
            return PartialView("_AccountModal", acc);
        }

        public ViewResult Created(Models.BankAccount account)
        {

            return View(account);
        }

        [ActionName("close")]
        public ActionResult CloseAccount()
        {
            var user = usersRepo.GetByEmail(User.Identity.Name);

PL.Web/Views/Service/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL.Web/Views/Service/Closed.cshtml
@model PL.WebApplication.Models.BankAccount
@{
    ViewBag.Title = "Closed";
}

@{ 
    ViewBag.Message = "The account is closed";
    ViewBag.LinkText = "view list of accounts";
    ViewBag.Action = "AccountsList";
}
@Html.Partial("_Done", Model)

PL.Web/Views/Service/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL.Web/Views/Service/Deposit.cshtml
@model IEnumerable<PL.WebApplication.Models.BankAccount>
@{
    ViewBag.Title = "Index";
}

@Html.Partial("_PageHeader", "Make a deposit")

@using (Html.BeginForm("DepositTo", "service"))
{
    @Html.Partial("_SelectAccount", Model)
}

PL.Web/Views/Service/DepositMade.cshtml
@model PL.WebApplication.Models.BankAccount
@{
    ViewBag.Title = "DepositMade";
}

@{
    ViewBag.Message = $"Deposit of {ViewBag.Amount.ToString("C")} is made";
    ViewBag.Action = "deposit";
    ViewBag.LinkText = "back to deposit page";
}
@Html.Partial("_Done", Model)

PL.Web/Views/Service/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@Html.Partial("_PageHeader", "Accounts service options")

<div class="list-group">
    <a href="@Url.Action("deposit")" class="list-group-item list-group-item-action"><span class="oi oi-arrow-thick-right"></span> Make a deposit </a>
    <a href="@Url.Action("withdraw")" class="list-group-item list-group-item-action"><span class="oi oi-arrow-thick-left"></span> Make a withdrawal </a>
    <a href="@Url.Action("transfer")" class="list-group-item list-group-item-action"><span class="oi oi-transfer"></span> Make a transfer </a>
    <a href="@Url.Action("create")" class="list-group-item list-group-item-action"><span class="oi oi-plus"></span> Create a new account </a>
    <a href="@Url.Action("close")" class="list-group-item list-group-item-action"><span class="oi oi-delete"></span> Close an account </a>
    <a href="@Url.Action("AccountsList")" class="list-group-item list-group-item-action"><span class="oi oi-list"></span> View list of accounts </a>
</div>

PL.Web/Views/Service/Transfer.cshtml
@model IEnumerable<PL.WebApplication.Models.BankAccount>
@{
    ViewBag.Title = "Transfer";
}

@Html.Partial("_PageHeader", "Make a transfer")

@using (Html.BeginForm())
{
    @Html.Partial("_SelectAccount", Model)
}

PL.Web/Views/Service/TransferToAnothers.cshtml
@model PL.WebApplication.Models.BankAccount

@{
    ViewBag.Title = "TransferToAnother";
}

@Html.Partial("_PageHeader", "Transfer to another's account")

<u class="h6">Transfer from:</u>
@Html.Partial("_AccountInfo", Model)

<hr />

<u class="h6">Transfer to:</u>
<div class="container">
    @using (Ajax.BeginForm("GetAnothersAccount", null, new AjaxOptions { UpdateTargetId = "response" }, new { @class = "my-2" }))
    {
        <div class="form-group row">
            @Html.Hidden("fromIBAN", Model.IBAN)
            <label for="iban" class="form-text">IBAN:</label>
            <input class="form-control mx-2" id="iban" name="iban" required />
            <button type="submit" class="btn btn-primary">Find</button>
        </div>
    }

    <div id="response"></div>
</div>


@Scripts.Render("~/scripts/jquery-3.0.0.min.js")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")

@section Scripts{
  
}

PL.Web/Views/Service/TransferToMy.cshtml
@model PL.WebApplication.Models.BankAccount

@{
    ViewBag.Title = "TransferToMy";
}

@Html.Partial("_PageHeader", "Transfer to my account")

<u class="h6">Transfer from:</u>
@Html.Partial("_AccountInfo", Model)

<hr />

<u class="h6">Transfer to:</u>
@{ViewBag.ButtonText = "Transfer";}

@using (Html.BeginForm("TransferToMyAmount", "service"))
{
    @Html.Hidden("fromIBAN", Model.IBAN)
    @Html.Partial("_SelectAccount", (IEnumerable<PL.WebApplication.Models.BankAccount>)ViewBag.Accounts)
}

PL.Web/Views/Service/TransferToMyAmount.cshtml
@model   PL.WebApplication.Models.BankAccount[]
@{
    ViewBag.Title = "TransferToMyAmount";
}

@Html.Partial("_PageHeader", "Transfer to my account")

<u class="h6">Transfer from:</u>
@Html.Partial("_AccountInfo", Model[0])

<u class="h6">Transfer to:</u>
@Html.Partial("_accountinfo", Model[1])

@using (Html.BeginForm("MakeTransfer", "service", FormMethod.Post, new { @class = "form-inline" }))
{
    @Html.Hidden("fromIBAN", Model[0].IBAN)
    @Html.Hidden("toIBAN", Model[1].IBAN)
    <label class="form-text ">Transfer amount:</label>
    <input type="number" name="amount" class="form-control mx-2 " required min="1" />
    <button type="submit" class="btn btn-primary">Transfer</button>
}

PL.Web/Views/Service/ViewAccountList.cshtml
@model IEnumerable<BLL.Interface.BankAccount>
@{
    ViewBag.Title = "ViewAccountList";
}

<h2>List of accounts</h2>

@*@Html.DisplayForModel()*@

<table rules="groups" cellpadding="3">
    <thead>
        <tr>
            <th>IBAN</th>
            <th>Owner</th>
            <th>Balance</th>
            <th>Bonus points</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var acc in Model)
        {
            <tr>
                <td align="center">@acc.IBAN</td>
                <td align="center">@acc.Owner</td>
                <td align="center">@acc.Balance</td>
                <td align="center">@acc.BonusPoints</td>
            </tr>
        }
    </tbody>
    <tfoot>

    </tfoot>
</table>

<h5>
    @Html.ActionLink("back to service", "Index", "Home")
</h5>

PL.Web/Views/Service/Withdraw.cshtml
@model IEnumerable<PL.WebApplication.Models.BankAccount>
@{
    ViewBag.Title = "Withdraw";
}

@Html.Partial("_PageHeader", "Make a withdrawal")

@using (Html.BeginForm("WithdrawFrom", "service"))
{
    @Html.Partial("_SelectAccount", Model)
}

PL.Web/Views/Service/WithdrawFrom.cshtml
@model PL.WebApplication.Models.BankAccount
@{
    ViewBag.Title = "WithdrawFrom";
}

@Html.Partial("_PageHeader", "Withdraw from account")

<u class="h6 ">Withdraw from:</u>
@Html.Partial("_AccountInfo", Model)

@Html.ValidationSummary(true, null, new { @class = "text-danger" })
@using (Html.BeginForm("MakeWithdrawal", "Service", Model, FormMethod.Post, new { @class = "form-inline" }))
{
    <div class="form-group">
        <label for="amount" class="form-text">Withdrawal amount:</label>
        <input name="amount" id="amount" class="form-control mx-2 " type="number" required min="1" max="1000000"/>
        <button type="button" class="btn btn-primary" data-toggle="modal_" data-target="#myModal" id="withdraw">Withdraw</button>
    </div>

    @Html.Partial("_AccountModal", Model)
}

@{
    ViewBag.Action = "withdraw";
    ViewBag.LinkText = "back to accounts list";
}
<br />
@Html.Partial("_BackLink")

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            $('#withdraw').click(function () {
                if ($("form")[0].checkValidity()) {
                    var amount = $("#amount").val();
                    $(".modal-title").text("Withdraw " + parseInt(amount).toLocaleString('en-US', { style: 'currency', currency: 'USD' }) + " from this account?");
                    $("#accountModal").modal();
                }
                else {
                    $(':submit').click();
                }
            });
        });
    </script>
}

PL.Web/Views/Service/WithdrawalMade.cshtml
@model PL.WebApplication.Models.BankAccount
@{
    ViewBag.Title = "WithdrawalMade";
}

@{
    ViewBag.Message = $"Withdrawal of {ViewBag.Amount.ToString("C")} is made";
    ViewBag.Action = "withdraw";
    ViewBag.LinkText = "back to withdraw page";
}
@Html.Partial("_Done", Model)